logging:
  level:
    ROOT: INFO
    com.abelm.blog_api: INFO

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:h2:mem:blogdb-prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  liquibase:
    enabled: false # Desactiva Liquibase

server:
  port: 8080
  shutdown: graceful

# application:
