logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com.abelm.blog_api: INFO

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: false # Desactiva Liquibase

server:
  port: 8080

coreprop:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    allow-credentials: true
    max-age: 1800

# application:
